#pragma once

#define BT_NAME "PCB HEATER"
#define BT_PASSWORD "9951"
#define BT_UARTPARAMS "115200,0,2"

#define GET_NAME_COMMAND "AT+NAME?"
#define GET_NAME_ANSWER "+NAME:" BT_NAME
#define SET_NAME_COMMAND "AT+NAME=" BT_NAME

#define GET_PSWD_COMMAND "AT+PSWD?"
#define GET_PSWD_ANSWER "+PSWD:" BT_PASSWORD
#define GET_PSWD_ANSWER2 "+PIN:\"" BT_PASSWORD "\""
#define SET_PSWD_COMMAND "AT+PSWD=" BT_PASSWORD
#define SET_PSWD_COMMAND2 "AT+PSWD=\"" BT_PASSWORD "\""

#define GET_UART_COMMAND "AT+UART?"
#define GET_UART_ANSWER "+UART:" BT_UARTPARAMS
#define SET_UART_COMMAND "AT+UART=" BT_UARTPARAMS

#define RESET_COMMAND "AT+RESET"

typedef enum
{
    HC05ERROR_NOERROR=0x00,
    HC05ERROR_NOTCONFIGURED_ERROR = 0x01,
    HC05ERROR_CONFIGURING_ERROR=0x02,
    HC05ERROR_NOANSWER=0x03,
} bt_error_t;

void hc05Init();
